### ISSUE TITLE
pair/triple/quadruple coding sessions

### ISSUE THREAD

**Issue by jcommelin** [leanprover-community/lftcm2020#5]
2 or 3 "curious mathematicians" together with a "lean expert".
Screensharing.
Every "curious mathematician" tries to write a bit of lean code. State a definition or theorem that you really like.
Interaction.

**Comment by kbuzzard** [comment]
Maybe it's better to trick the curious mathematicians into doing something which is already known to come out really nicely in Lean, e.g. checking that the subgroups of a group are a lattice, as opposed to e.g. proving that the order of the element divides the order of the group, which is kind of a nightmare because finiteness is a subtle concept in type theory.
